name: 🐳 Publish LOLALYTICS-URF

on:
  workflow_run:
    workflows: ["Trigger Publish URF"]
    types:
      - completed
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@master
        with:
          node-version: 'lts/*'

      - name: Download && Execute
        env:
          GH_TOKEN: ${{ secrets.GH_DOWNLOAD_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          release_name=$(gh api -H "Accept: application/vnd.github+json" /repos/cangzhang/data-maker/releases/latest --jq ".name")
          gh release download "$release_name" -R cangzhang/data-maker -p "*-linux*" -D bin
          cd bin && chmod +x data-maker-linux-amd64 && mv data-maker* data-maker
          ./data-maker -v && ./data-maker -s lolalytics-urf
          npm install -g --quiet @jsdevtools/npm-publish
          curl https://gist.githubusercontent.com/cangzhang/1bdb2f37e4c5770ac703ee5afec600f5/raw/ci-publish.sh -o publish.sh && chmod +x publish.sh
          ./publish.sh

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            bin/output/*
